In [1]:
from massspecgym.data.datasets import MSnDataset, MassSpecDataset
from massspecgym.data.transforms import MolFingerprinter, SpecTokenizer
from massspecgym.data import MassSpecDataModule
from massspecgym.featurize import SpectrumFeaturizer
import torch

In [2]:
file_mgf = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_msn_library_pos_all_lib_MSn.mgf"
file_json = "/Users/macbook/CODE/Majer:MassSpecGym/data/Retrieval/MassSpecGym_retrieval_candidates_mass.json"
split_file = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_split.tsv"
pth_massspecgym_original = "/Users/macbook/CODE/Majer:MassSpecGym/data/MassSpecGym/MassSpecGym.tsv"

In [3]:
# Init hyperparameters
n_peaks = 60
batch_size = 12

# Load dataset
dataset_original = MassSpecDataset(
    pth=pth_massspecgym_original,
    spec_transform=SpecTokenizer(n_peaks=n_peaks),
    mol_transform=None,
)

In [4]:
# Init data module
data_module_original = MassSpecDataModule(
    dataset=dataset_original,
    batch_size=batch_size,
    num_workers=0,
)

In [5]:
data_module_original.prepare_data()
data_module_original.setup()

train_loader_original = data_module_original.train_dataloader()

Train dataset size: 194119
Val dataset size: 19429


In [6]:
tmp_original = []
for batch in train_loader_original:
    print(batch)
    tmp_original = batch
    break

{'spec': tensor([[[2.4616e+02, 1.1000e+00],
         [5.3003e+01, 5.5011e-04],
         [5.3998e+01, 5.8460e-04],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[7.8459e+02, 1.1000e+00],
         [1.6613e+02, 1.3962e-03],
         [1.8400e+02, 1.0000e+00],
         ...,
         [7.8479e+02, 1.7289e-02],
         [7.8569e+02, 2.7631e-03],
         [7.8685e+02, 5.1936e-04]],

        [[3.2414e+02, 1.1000e+00],
         [9.6044e+01, 1.5864e-01],
         [9.7051e+01, 6.2263e-02],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        ...,

        [[3.5512e+02, 1.1000e+00],
         [9.1054e+01, 1.0000e-02],
         [1.0704e+02, 1.0000e-02],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.7609e+02, 1.1000e+00],
         [4.1039e+01, 1.3390e-02],
   

In [7]:
# Check the keys in the batch
print(tmp_original.keys())

# Specifically check if 'batch_ptr' is present
if 'batch_ptr' in tmp_original:
    print("batch_ptr is present:", tmp_original['batch_ptr'])
else:
    print("batch_ptr is missing")

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'mol_freq', 'identifier'])
batch_ptr is missing


In [8]:
tmp_original['spec'].shape

torch.Size([12, 61, 2])

In [9]:
tmp_original['mol']

['CCCCCCC(=O)NCCC1=NC=CN1',
 'CCCCCCCCCCCCCCCC(=O)OC[C@H](COP(=O)([O-])OCC[N+](C)(C)C)OC(=O)CCCCCC/C=C/C/C=C/C/C=C/CCCCC',
 'CC(=O)NC1C(C2C(COC(O2)C3=CC=CC=C3)OC1OC)O',
 'COC1=C(C2=C(C=C1O)OC(=CC2=O)C3=CC=C(C=C3)O)O',
 'C1=CC=C(C(=C1)C(=O)CC(C(=O)O)N)N',
 'COC1=C(C=CC(=C1)C2C3(COC(C3(CO2)O)C4=CC(=C(C=C4)O[C@H]5[C@@H]([C@H]([C@@H]([C@H](O5)CO)O)O)O)OC)O)O',
 'CN1C(=C(C2=C(S1(=O)=O)C=CS2)O)C(=O)NC3=CC=CC=N3',
 'C[C@]12CC[C@@H](C[C@]1(CC[C@@H]3[C@@H]2CC[C@]4([C@@]3(CC[C@@H]4C5=COC(=O)C=C5)O)C)O)O',
 'C1=CC=C(C=C1)C[C@@H](C(=O)O)N',
 'CC(=O)OC1=CC=C(C=C1)/C=C/C2=CC(=CC(=C2)OC(=O)C)OC(=O)C',
 'C/C=C\\N1C=NC2=C(N=CN=C21)N',
 'C1=C2C3=C(C(=C1O)O)OC(=O)C4=CC(=C(C(=C43)OC2=O)O)O']

In [10]:
tmp_original['precursor_mz']

tensor([246.1580, 784.5860, 324.1450, 301.0700, 209.0927, 575.1740, 338.0300,
        403.2479, 166.0863, 355.1176, 176.0931, 303.0100])

In [11]:
tmp_original['adduct']

['[M+Na]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+Na]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+']

In [12]:
tmp_original['mol_freq']

tensor([  3., 304.,   1.,  28.,  98.,   2.,  21.,  13., 138.,  30.,   2., 322.])

In [13]:
tmp_original['identifier']

['MassSpecGymID0391910',
 'MassSpecGymID0403818',
 'MassSpecGymID0398810',
 'MassSpecGymID0195961',
 'MassSpecGymID0161786',
 'MassSpecGymID0193760',
 'MassSpecGymID0052238',
 'MassSpecGymID0222508',
 'MassSpecGymID0067472',
 'MassSpecGymID0106450',
 'MassSpecGymID0235596',
 'MassSpecGymID0167182']

# MSn

In [14]:
config = {
    'features': ['collision_energy', 'ionmode', 'adduct', 'spectrum_stats', 'atom_counts', 'value', "retention_time", 'ion_source', 'binned_peaks'],
    'feature_attributes': {
        'atom_counts': {
            'top_n_atoms': 12,
            'include_other': True,
        },
    },
}

In [15]:
featurizer = SpectrumFeaturizer(config, mode='torch')

In [16]:
# Init hyperparameters
batch_size = 12

msn_dataset = MSnDataset(
    pth=file_mgf,
    featurizer=featurizer,
    mol_transform=None,
    max_allowed_deviation=0.005
)

In [17]:
data_module_msn = MassSpecDataModule(
    dataset=msn_dataset,
    batch_size=batch_size,
    split_pth=split_file,
    num_workers=0,
)

In [18]:
data_module_msn.prepare_data()
data_module_msn.setup()

train_loader_msn = data_module_msn.train_dataloader()

Train dataset size: 12536
Val dataset size: 1952


In [19]:
tmp_msn = []
for batch in train_loader_msn:
    print(batch)
    tmp_msn = batch
    break

{'spec': DataBatch(x=[134, 1039], edge_index=[2, 122], batch=[134], ptr=[13]), 'mol': ['COC1=C(C2=C[N+]3=C(C=C2C=C1)C4=CC(=C(C=C4CC3)O)O)OC', 'C1OC2=C(O1)C=C(C=C2)CNC3=C(N=C(O3)CC4=CC=CC5=CC=CC=C54)C#N', 'COC(=O)C1=CC=CC=C1NC(=O)N[C@@H](CC2=CNC3=CC=CC=C32)C(=O)OC', 'C1CN(CCC1=C(C2=CC=C(C=C2)F)C3=CC=C(C=C3)F)CCN4C(=O)C5=CC=CC=C5NC4=S', 'COCC1=CC(=CN=C1)C2=CC3=C(N=C2)N(CCC3)C(=O)N', 'CC[C@@H](C)[C@@H](C(=O)O)NC(=O)C1=CC2=C(C=C1)N(C=C2)C', 'C1=C(C=C(C(=C1O)O)O)C(=O)O[C@@H]2[C@H](O[C@H]([C@@H]([C@H]2OC(=O)C3=CC(=C(C(=C3)O)O)O)OC(=O)C4=CC(=C(C(=C4)O)O)O)OC(=O)C5=CC(=C(C(=C5)O)O)O)CO', 'CCCCN(C)C(=O)CN1C2=CC=CC=C2N=C1CN(C)C(=O)C3=CC=CO3', 'C=C1C(CC2C1C(OC=C2C(=O)O)OC3C(C(C(C(O3)CO)O)O)OC(=O)/C=C/C4=CC=C(C=C4)O)O', 'CO[C@H]1C(O[C@H](CO1)[C@@H](COCC2=CC=CC=C2)OCC3=CC=CC=C3)O', 'CC(C)(C)N1C=C(N=N1)CN(CC2=CN(N=N2)CC(=O)O)CC3=CN(N=N3)C(C)(C)C', 'C1CN2CCC1C3=C2SC(=C3C#N)N=CC4=C(C=C(C=C4)O)O'], 'precursor_mz': tensor([324.1230, 384.1343, 396.1554, 490.1759, 299.1502, 289.1547, 806.1411,
        383

In [20]:
# Check the keys in the batch
print(tmp_msn.keys())

# Specifically check if 'batch_ptr' is present
if 'batch_ptr' in tmp_msn:
    print("batch_ptr is present:", tmp_msn['batch_ptr'])
else:
    print("batch_ptr is missing")

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'identifier', 'mol_freq'])
batch_ptr is missing


In [21]:
tmp_msn['spec']

DataBatch(x=[134, 1039], edge_index=[2, 122], batch=[134], ptr=[13])

In [22]:
tmp_msn['mol']

['COC1=C(C2=C[N+]3=C(C=C2C=C1)C4=CC(=C(C=C4CC3)O)O)OC',
 'C1OC2=C(O1)C=C(C=C2)CNC3=C(N=C(O3)CC4=CC=CC5=CC=CC=C54)C#N',
 'COC(=O)C1=CC=CC=C1NC(=O)N[C@@H](CC2=CNC3=CC=CC=C32)C(=O)OC',
 'C1CN(CCC1=C(C2=CC=C(C=C2)F)C3=CC=C(C=C3)F)CCN4C(=O)C5=CC=CC=C5NC4=S',
 'COCC1=CC(=CN=C1)C2=CC3=C(N=C2)N(CCC3)C(=O)N',
 'CC[C@@H](C)[C@@H](C(=O)O)NC(=O)C1=CC2=C(C=C1)N(C=C2)C',
 'C1=C(C=C(C(=C1O)O)O)C(=O)O[C@@H]2[C@H](O[C@H]([C@@H]([C@H]2OC(=O)C3=CC(=C(C(=C3)O)O)O)OC(=O)C4=CC(=C(C(=C4)O)O)O)OC(=O)C5=CC(=C(C(=C5)O)O)O)CO',
 'CCCCN(C)C(=O)CN1C2=CC=CC=C2N=C1CN(C)C(=O)C3=CC=CO3',
 'C=C1C(CC2C1C(OC=C2C(=O)O)OC3C(C(C(C(O3)CO)O)O)OC(=O)/C=C/C4=CC=C(C=C4)O)O',
 'CO[C@H]1C(O[C@H](CO1)[C@@H](COCC2=CC=CC=C2)OCC3=CC=CC=C3)O',
 'CC(C)(C)N1C=C(N=N1)CN(CC2=CN(N=N2)CC(=O)O)CC3=CN(N=N3)C(C)(C)C',
 'C1CN2CCC1C3=C2SC(=C3C#N)N=CC4=C(C=C(C=C4)O)O']

In [23]:
tmp_msn['precursor_mz']

tensor([324.1230, 384.1343, 396.1554, 490.1759, 299.1502, 289.1547, 806.1411,
        383.2078, 538.1919, 397.1622, 431.2626, 326.0958])

In [24]:
tmp_msn['adduct']

['[M]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+NH4]+',
 '[M+H]+',
 '[M+NH4]+',
 '[M+Na]+',
 '[M+H]+',
 '[M+H]+']

In [25]:
tmp_msn['mol_freq']

tensor([1., 1., 1., 1., 1., 1., 1., 1., 3., 2., 1., 2.])

In [26]:
tmp_msn['identifier']

['0091223_0000000',
 '0047252_0000000',
 '0049284_0000000',
 '0087371_0000000',
 '0080314_0000000',
 '0050743_0000000',
 '0003907_0000000',
 '0042012_0000000',
 '0004982_0000000',
 '0045251_0000000',
 '0058733_0000000',
 '0039635_0000000']

In [27]:
tmp_msn['identifier']

['0091223_0000000',
 '0047252_0000000',
 '0049284_0000000',
 '0087371_0000000',
 '0080314_0000000',
 '0050743_0000000',
 '0003907_0000000',
 '0042012_0000000',
 '0004982_0000000',
 '0045251_0000000',
 '0058733_0000000',
 '0039635_0000000']