In [1]:
import json
from matchms.importing import load_from_mgf
from rdkit import Chem
# from massspecgym.tools.analyzers import analyze_canonical_smiles
import os

In [2]:
import importlib
import massspecgym.data.transforms as transforms
import massspecgym.data.datasets as datasets
import massspecgym.data.data_module as data_module




In [3]:
from massspecgym.data.transforms import MolFingerprinter, MolToInChIKey, MolToFormulaVector, SpecTokenizer
from massspecgym.data.datasets import MSnDataset, MSnRetrievalDataset, RetrievalDataset
from massspecgym.data.data_module import MassSpecDataModule

In [4]:
file_mgf = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_msn_library_pos_all_lib_MSn.mgf"
file_json = "/Users/macbook/CODE/Majer:MassSpecGym/data/Retrieval/MassSpecGym_retrieval_candidates_mass.json"
split_file = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_split.tsv"

In [5]:
from massspecgym.data.transforms import MolFingerprinter, MolToInChIKey, MolToFormulaVector, SpecTokenizer
# from massspecgym.data.datasets import MSnDataset, MSnRetrievalDataset
# from massspecgym.featurize import SpectrumFeaturizer
# from massspecgym.data.data_module import MassSpecDataModule
from massspecgym.data import RetrievalDataset, MassSpecDataModule

In [6]:
pth_massspecgym_original = "/Users/macbook/CODE/Majer:MassSpecGym/data/MassSpecGym/MassSpecGym.tsv"

In [7]:
# Init hyperparameters
n_peaks = 60
fp_size = 4096
batch_size = 12

# Load dataset
dataset_original = RetrievalDataset(
    pth=pth_massspecgym_original,
    candidates_pth=file_json,
    spec_transform=SpecTokenizer(n_peaks=n_peaks),
    mol_transform=MolFingerprinter(fp_size=fp_size),
)


In [8]:
# Init data module
data_module_original = MassSpecDataModule(
    dataset=dataset_original,
    batch_size=batch_size,
    split_pth=split_file,
    num_workers=0,
)

In [9]:
data_module_original.prepare_data()
data_module_original.setup()

train_loader_original = data_module_original.train_dataloader()

here i am two
Train dataset size: 194119
Val dataset size: 19429


In [10]:
tmp = []
for batch in train_loader_original:
    print(batch)
    tmp = batch
    break

I am not here
{'spec': tensor([[[4.1522e+02, 1.1000e+00],
         [1.1010e+02, 2.8028e-02],
         [1.7506e+02, 3.2032e-02],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.6910e+02, 1.1000e+00],
         [5.3002e+01, 3.6756e-03],
         [5.3038e+01, 7.2379e-03],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[2.9018e+02, 1.1000e+00],
         [7.7041e+01, 5.0050e-03],
         [9.1052e+01, 6.0060e-03],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        ...,

        [[2.5009e+02, 1.1000e+00],
         [2.4908e+02, 1.0010e-03],
         [2.5009e+02, 1.0000e+00],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[2.1510e+02, 1.1000e+00],
         [5.7070e+01, 1.

In [11]:
# Check the keys in the batch
print(tmp.keys())

# Specifically check if 'batch_ptr' is present
if 'batch_ptr' in tmp:
    print("batch_ptr is present:", tmp['batch_ptr'])
else:
    print("batch_ptr is missing")

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'mol_freq', 'identifier', 'smiles', 'candidates', 'labels', 'batch_ptr', 'candidates_smiles'])
batch_ptr is present: tensor([256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256])


In [12]:
tmp.keys()

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'mol_freq', 'identifier', 'smiles', 'candidates', 'labels', 'batch_ptr', 'candidates_smiles'])

In [13]:
tmp['spec'].shape, tmp['mol'].shape, 

(torch.Size([12, 61, 2]), torch.Size([12, 4096]))

In [14]:
tmp['precursor_mz']

tensor([415.2227, 169.0970, 290.1751, 302.1757, 320.1500, 226.1444, 217.0500,
        301.0700, 311.0809, 250.0863, 215.0961, 136.0618])

In [15]:
tmp['adduct'], 

(['[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+'],)

In [16]:
tmp['mol_freq']

tensor([ 20.,  50., 254.,  12.,  52.,  32., 180.,  33.,  87.,  15.,  56.,  99.])

In [17]:
tmp['labels']

tensor([ True, False, False,  ..., False, False, False])

In [18]:
len(tmp['labels'])

3072

In [19]:
tmp['batch_ptr']

tensor([256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [20]:
sum(tmp['batch_ptr'])

tensor(3072)

In [21]:
len(tmp['candidates'])

3072

In [22]:
tmp['candidates'][5].shape

torch.Size([4096])

In [23]:
len(tmp['candidates_smiles'])

3072

# MSnRetrieval

In [6]:
from massspecgym.featurize import SpectrumFeaturizer

In [7]:
file_mgf = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_msn_library_pos_all_lib_MSn.mgf"
file_json = "/Users/macbook/CODE/Majer:MassSpecGym/data/Retrieval/MassSpecGym_retrieval_candidates_mass.json"
split_file = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_split.tsv"

In [8]:
config = {
    'features': ['collision_energy', 'ionmode', 'adduct', 'spectrum_stats', 'atom_counts', 'value', "retention_time", 'ion_source', 'binned_peaks'],
    'feature_attributes': {
        'atom_counts': {
            'top_n_atoms': 12,
            'include_other': True,
        },
    },
}

In [9]:
featurizer = SpectrumFeaturizer(config, mode='torch')

In [10]:
# Init hyperparameters
n_peaks = 60
fp_size = 4096
batch_size = 12

# Load dataset
dataset_original = MSnRetrievalDataset(
    pth=file_mgf,
    candidates_pth=file_json,
    featurizer=featurizer,
    mol_transform=MolFingerprinter(fp_size=fp_size),
    max_allowed_deviation=0.005
)


Total valid indices: 15674
Dataset length: 15674


In [11]:
# (pth="/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20240929_msn_library_pos_all_lib_MSn.mgf",
#                          mol_transform=mol_transform,
#                          featurizer=featurizer,
#                          max_allowed_deviation=0.005)

In [12]:
# Init data module
data_module_original = MassSpecDataModule(
    dataset=dataset_original,
    batch_size=batch_size,
    split_pth=split_file,
    num_workers=0,
)

In [13]:
data_module_original.prepare_data()
data_module_original.setup()

train_loader_original = data_module_original.train_dataloader()

Train dataset size: 11883
Val dataset size: 1899


In [14]:
tmp = []
for batch in train_loader_original:
    print(batch)
    tmp = batch
    break

in getitem
3517
in getitem
12669
in getitem
6018
in getitem
9609
in getitem
9679
in getitem
2470
in getitem
15076
in getitem
7261
in getitem
5952
in getitem
114
in getitem
10599
in getitem
499
in collate_fn
{'spec': DataBatch(x=[114, 1039], edge_index=[2, 102], batch=[114], ptr=[13]), 'mol': tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]), 'precursor_mz': tensor([ 436.1535,  397.1870,  330.1349,  534.2475,  491.1411,  542.1868,
         354.1255,  353.1496,  342.1812, 1137.6051,  509.2314,  310.0921]), 'adduct': ['[M+H]+', '[M+H]+', '[M+H]+', '[M+H]+', '[M+H]+', '[M+NH4]+', '[M+H]+', '[M+H]+', '[M+H]+', '[M+H]+', '[M+H]+', '[M+H]+'], 'identifier': ['0023348_0000000', '0081146_0000000', '0039128_0000000', '0061787_0000000', '0062250_0000000', '0016499_0000000', '0096700_0000000', '004

In [15]:
# Check the keys in the batch
print(tmp.keys())

# Specifically check if 'batch_ptr' is present
if 'batch_ptr' in tmp:
    print("batch_ptr is present:", tmp['batch_ptr'])
else:
    print("batch_ptr is missing")

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'identifier', 'mol_freq', 'smiles', 'candidates', 'labels', 'batch_ptr', 'candidates_smiles'])
batch_ptr is present: tensor([256, 256, 256, 256, 256, 256, 256, 256, 256, 210, 256, 256])


#### Shold be dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'mol_freq', 'identifier', 'smiles', 'candidates', 'labels', 'batch_ptr', 'candidates_smiles'])

In [16]:
tmp.keys()

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'identifier', 'mol_freq', 'smiles', 'candidates', 'labels', 'batch_ptr', 'candidates_smiles'])

In [17]:
tmp['spec'] 

DataBatch(x=[114, 1039], edge_index=[2, 102], batch=[114], ptr=[13])

In [18]:
tmp['precursor_mz']

tensor([ 436.1535,  397.1870,  330.1349,  534.2475,  491.1411,  542.1868,
         354.1255,  353.1496,  342.1812, 1137.6051,  509.2314,  310.0921])

In [19]:
tmp['mol_freq']

tensor([1., 1., 1., 4., 1., 1., 1., 1., 1., 2., 1., 1.])

In [20]:
tmp['identifier']

['0023348_0000000',
 '0081146_0000000',
 '0039128_0000000',
 '0061787_0000000',
 '0062250_0000000',
 '0016499_0000000',
 '0096700_0000000',
 '0046892_0000000',
 '0038726_0000000',
 '0000741_0000000',
 '0068067_0000000',
 '0003286_0000000']

In [21]:
tmp['adduct']

['[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+NH4]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+',
 '[M+H]+']

In [22]:
tmp['mol'].shape

torch.Size([12, 4096])

In [23]:
tmp['smiles']

['CC1=CC(=CC=C1)C2=NC(=C(O2)C)CN3C(=C(N=N3)C(=O)NCC4=CC(=CC=C4)Cl)C',
 'C1CC(CCC1CC(=O)O)C2=CC=C(C=C2)N3CCOC4=NC=NC(=C4C3=O)N',
 'C1CN(C2=NC3=CC=CC=C3N21)C(=O)C4=NC=CC(=C4)N5C=CC=C5',
 'CNC(=O)CCC1=CC(=NN1C2=CC=C(C=C2)N3CCNCC3)C4=CC=C(C=C4)C5=CC=C(C=C5)C(F)(F)F',
 'CN1C[C@H]2CC(C[C@H]2C1)COC3=C(C=C4C(=C3)N=CN=C4NC5=C(C(=C(C=C5)Cl)Cl)F)OC',
 'COC1=C(C=CC(=C1)C(=O)OCC2=CCC3C2C(OC=C3C(=O)O)O[C@H]4[C@@H]([C@H]([C@@H]([C@H](O4)CO)O)O)O)O',
 'CCCC(C1=C(N=C2C=CC(=CC2=C1C3=CC=CC=C3)Cl)C)C(=O)O',
 'CC1=CC=CC=C1OCC(=O)NC(CC2=CNC3=CC=CC=C32)C(=O)O',
 'CC(C)N1CCC(C1=O)N2CC3C(C2)C(=O)N(C3=O)C4=CC=CC=C4',
 'CC1C(C(CC(O1)O[C@H]2CC[C@@]3(C4[C@@H]([C@H]([C@@]5([C@H](CC[C@@]5([C@@]4(CC=C3C2)O)O)[C@H](C)O)C)O)O)C)OC)OC6CC(C(C(O6)C)OC7CC(C(C(O7)C)OC8C(C(C(C(O8)C)OC9C(C(C(C(O9)CO)O)O)O)OC)O)OC)OC',
 'CC1=C(C(=NO1)C)C2=CC3=C(C=C2)N(C(=N3)CCC4=CC(=C(C=C4)OC)Cl)C[C@H](C)N5CCOCC5',
 'CC1=CC2=C(C(=C1O)OC)C(=O)C(=C(O2)NC(C)C(=O)O)O']

In [24]:
tmp['labels']

tensor([ True, False, False,  ..., False, False, False])

In [25]:
len(tmp['labels'])

3026

In [26]:
tmp['batch_ptr']

tensor([256, 256, 256, 256, 256, 256, 256, 256, 256, 210, 256, 256])

In [27]:
sum(tmp['batch_ptr'])

tensor(3026)

In [28]:
len(tmp['candidates'])

3026

In [29]:
tmp['candidates'][5].shape

torch.Size([4096])