In [1]:
import json
from matchms.importing import load_from_mgf
from rdkit import Chem
# from massspecgym.tools.analyzers import analyze_canonical_smiles
import os

In [2]:
import importlib
import massspecgym.data.transforms as transforms
import massspecgym.data.datasets as datasets
import massspecgym.data.data_module as data_module

importlib.reload(transforms)
importlib.reload(datasets)
importlib.reload(data_module)

<module 'massspecgym.data.data_module' from '/Users/macbook/CODE/Majer:MassSpecGym/massspecgym/data/data_module.py'>

In [3]:
from massspecgym.data.transforms import MolFingerprinter, MolToInChIKey, MolToFormulaVector, SpecTokenizer
# from massspecgym.data.datasets import MSnDataset, MSnRetrievalDataset, RetrievalDataset
from massspecgym.data.data_module import MassSpecDataModule

In [4]:
file_mgf = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20241211_msn_library_pos_all_lib_MSn.mgf"
file_json = "/Users/macbook/CODE/Majer:MassSpecGym/data/Retrieval/MassSpecGym_retrieval_candidates_mass.json"
split_file = "/Users/macbook/CODE/Majer:MassSpecGym/data/MSn/20240929_split.tsv"

In [5]:
from massspecgym.data.transforms import MolFingerprinter, MolToInChIKey, MolToFormulaVector, SpecTokenizer
# from massspecgym.data.datasets import MSnDataset, MSnRetrievalDataset
# from massspecgym.featurize import SpectrumFeaturizer
# from massspecgym.data.data_module import MassSpecDataModule
from massspecgym.data import RetrievalDataset, MassSpecDataModule

In [6]:
pth_massspecgym_original = "/Users/macbook/CODE/Majer:MassSpecGym/data/MassSpecGym/MassSpecGym.tsv"

In [7]:
# Init hyperparameters
n_peaks = 60
fp_size = 4096
batch_size = 12

# Load dataset
dataset_original = RetrievalDataset(
    pth=pth_massspecgym_original,
    candidates_pth=file_json,
    spec_transform=SpecTokenizer(n_peaks=n_peaks),
    mol_transform=MolFingerprinter(fp_size=fp_size),
)


In [8]:
# Init data module
data_module_original = MassSpecDataModule(
    dataset=dataset_original,
    batch_size=batch_size,
    num_workers=0,
)

In [9]:
data_module_original.prepare_data()
data_module_original.setup()

train_loader_original = data_module_original.train_dataloader()

here i am two
Train dataset size: 194119
Val dataset size: 19429


In [10]:
tmp = []
for batch in train_loader_original:
    print(batch)
    tmp = batch
    break

I am not here
{'spec': tensor([[[2.8013e+02, 1.1000e+00],
         [5.5018e+01, 3.0508e-02],
         [6.5039e+01, 8.2744e-04],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[2.8706e+02, 1.1000e+00],
         [6.7258e+01, 1.9400e-03],
         [6.7263e+01, 2.0200e-03],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[2.4412e+02, 1.1000e+00],
         [4.1039e+01, 3.1800e-02],
         [4.2010e+01, 4.2100e-03],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        ...,

        [[1.3904e+02, 1.1000e+00],
         [5.0015e+01, 1.3038e-03],
         [5.1023e+01, 5.1271e-03],
         ...,
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[4.5504e+02, 1.1000e+00],
         [5.7045e+01, 3.

In [11]:
# Check the keys in the batch
print(tmp.keys())

# Specifically check if 'batch_ptr' is present
if 'batch_ptr' in tmp:
    print("batch_ptr is present:", tmp['batch_ptr'])
else:
    print("batch_ptr is missing")

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'mol_freq', 'identifier', 'smiles', 'candidates', 'labels', 'batch_ptr', 'candidates_smiles'])
batch_ptr is present: tensor([256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256])


In [12]:
tmp.keys()

dict_keys(['spec', 'mol', 'precursor_mz', 'adduct', 'mol_freq', 'identifier', 'smiles', 'candidates', 'labels', 'batch_ptr', 'candidates_smiles'])

In [13]:
tmp['spec'].shape, tmp['mol'].shape, 

(torch.Size([12, 61, 2]), torch.Size([12, 4096]))

In [14]:
tmp['precursor_mz']

tensor([280.1330, 287.0550, 244.1180, 235.1441, 779.4500, 269.0355, 237.0760,
        295.1810, 199.0633, 139.0390, 455.0373, 409.0645])

In [15]:
tmp['adduct'], 

(['[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+Na]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+',
  '[M+H]+'],)

In [16]:
tmp['labels']

tensor([ True, False, False,  ..., False, False, False])

In [20]:
len(tmp['labels'])

3072

In [21]:
tmp['batch_ptr']

tensor([256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [22]:
sum(tmp['batch_ptr'])

tensor(3072)

In [17]:
len(tmp['candidates'])

3072

In [18]:
tmp['candidates'][5].shape

torch.Size([4096])

In [19]:
len(tmp['candidates_smiles'])

3072